import type { Metadata } from "next";
import { outfit } from "@/fonts";
import "./globals.css";
import { AppProviders } from "@/context/AppProviders";
import { getCartIdFromCookies } from "@/services/cart-service";
import NavbarContainer from "@/ui/navbar/NavbarContainer";
import FooterContainer from "@/ui/footer/FooterContainer";
import { getCart } from "@/lib/shopify/api/cart";

import Loader from "@/components/Loader";
import Notification from "@/components/Notification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = await getCartIdFromCookies();
  const cart = await getCart(cartId);

  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased flex flex-col flex-1`}>
        <AppProviders shopifyCart={cart}>
          <Loader />
          <Notification />
          <NavbarContainer />
          <div className="min-h-[100vh]">{children}</div>
          <FooterContainer />
        </AppProviders>
      </body>
    </html>
  );
}
