import type { Metadata } from "next";
import Script from "next/script";
import { outfit } from "@/fonts";
import "./globals.css";

import { AppProviders } from "@/context/AppProviders";
import { getCartIdFromCookies } from "@/services/cart-service";
import { getCart } from "@/lib/shopify/api/cart";

import Loader from "@/components/shared/Loader";
import FooterContainer from "@/components/footer/FooterContainer";
import NavbarContainer from "@/components/navbar/NavbarContainer";
import Notification from "@/components/shared/Notification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = await getCartIdFromCookies();
  const cart = await getCart(cartId);

  return (
    <html lang="en" className="scroll-smooth">
      {/**
       * @todo organize this Analytics config later
       */}
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.ANALYTICS_TRACKING_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', "${process.env.ANALYTICS_TRACKING_ID}");
        `}
        </Script>
      </head>
      <body className={`${outfit.className} antialiased flex flex-col flex-1`}>
        <AppProviders shopifyCart={cart}>
          <Loader />
          <Notification />
          <NavbarContainer />
          <div className="min-h-[100vh]">{children}</div>
          <FooterContainer />
        </AppProviders>
      </body>
    </html>
  );
}
